title = "this is the configuration file of the redpitaya plugin !!!!!!"
ip_address = "169.254.121.34"
port = 5000

[sampling]
decimation = 128
nsamples = 2000
gain1 = "HV"
gain2 = "HV"

[trigger]
source = "CH1_PE"
level = 0.0
center_trigger = true

[generator]
gen_trigger = "INT"
enabling = false
amplitude = 1
frequency = 1000
shape = "DC"
offset = 0
phase = 0
cycle = 0.5
channel = 1
piezo_channel = 'x'

[Scaling]
scaling = 50e-6
use_scaling = true
offset2 = 0

[sweep]
sweep_modes = "LINEAR"
sweep_start_frequency = 10
sweep_stop_frequency = 1000000.0
sweep_time = 1000000.0
sweep_decimation = 64
sweep_nsamples = 8000
direction = "NORMAL"

[counting]
port_count = 5555
port_count_1D = 5556
threshold = 200 #200 is a good value for signals of +-1V
deadtime = 0
gate_ms = 10
history = 1000
stream_length = 5
stream_ms = 20
histogram = false